/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import daoimpl.BrokerDAOImpl;
import daoimpl.CompanyDAOImpl;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableRowSorter;
import models.BrokerModel;
import models.CompanyModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo
 */
public class CompanyFrame extends javax.swing.JFrame {

    /**
     * Creates new form CompanyFrame
     */
    public CompanyFrame() {
        initComponents();
        populateCompanyTable();
        disableButtons(1);
        this.setLocationRelativeTo(null);
        companyNameField.requestFocus();
        companyTable.setDefaultEditor(Object.class, null);
        companyNameField.requestFocus();
        this.setExtendedState(CompanyFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeletePopupMenu = new javax.swing.JPopupMenu();
        deleteMenu = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        companyNameField = new javax.swing.JTextField();
        contactPersonField = new javax.swing.JTextField();
        addCompanyButton = new javax.swing.JLabel();
        updateCompanyButton = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrolPane = new javax.swing.JScrollPane();
        companyTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        searchCompanyField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        clearFieldButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        deleteMenu.setText("Delete Row");
        deleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuActionPerformed(evt);
            }
        });
        DeletePopupMenu.add(deleteMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Company Name : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 35));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Contact Person :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 40));

        companyNameField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        companyNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                companyNameFieldKeyReleased(evt);
            }
        });
        jPanel2.add(companyNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 277, 40));

        contactPersonField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        contactPersonField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactPersonFieldKeyTyped(evt);
            }
        });
        jPanel2.add(contactPersonField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 280, 40));

        addCompanyButton.setBackground(new java.awt.Color(140, 198, 62));
        addCompanyButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        addCompanyButton.setForeground(new java.awt.Color(255, 255, 255));
        addCompanyButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCompanyButton.setText("Add Company");
        addCompanyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCompanyButton.setOpaque(true);
        addCompanyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCompanyButtonMouseClicked(evt);
            }
        });
        jPanel2.add(addCompanyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 170, 40));

        updateCompanyButton.setBackground(new java.awt.Color(140, 198, 62));
        updateCompanyButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        updateCompanyButton.setForeground(new java.awt.Color(255, 255, 255));
        updateCompanyButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateCompanyButton.setText("Update Company");
        updateCompanyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCompanyButton.setOpaque(true);
        updateCompanyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateCompanyButtonMouseClicked(evt);
            }
        });
        jPanel2.add(updateCompanyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 170, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Company Record");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        companyTable.setAutoCreateRowSorter(true);
        companyTable.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        companyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        companyTable.setRowHeight(20);
        companyTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        companyTable.setSelectionForeground(new java.awt.Color(140, 168, 62));
        companyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                companyTableMouseReleased(evt);
            }
        });
        companyTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                companyTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                companyTableKeyReleased(evt);
            }
        });
        jScrolPane.setViewportView(companyTable);

        jPanel2.add(jScrolPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 840, 550));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search Company");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 170, 40));

        searchCompanyField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        searchCompanyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCompanyFieldActionPerformed(evt);
            }
        });
        searchCompanyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchCompanyFieldKeyReleased(evt);
            }
        });
        jPanel2.add(searchCompanyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 370, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Address :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 90, 40));

        cityField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 280, 40));

        addressField.setColumns(20);
        addressField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addressField.setRows(5);
        jScrollPane1.setViewportView(addressField);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 280, 120));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("City :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 70, 40));

        clearFieldButton.setBackground(new java.awt.Color(140, 198, 62));
        clearFieldButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        clearFieldButton.setForeground(new java.awt.Color(255, 255, 255));
        clearFieldButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clearFieldButton.setText("Clear");
        clearFieldButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearFieldButton.setOpaque(true);
        clearFieldButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearFieldButtonMouseClicked(evt);
            }
        });
        jPanel2.add(clearFieldButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 370, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 680));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 23, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 198, 62));
        jLabel1.setText("Company");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Update");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Delete");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Reset");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Back");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCompanyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCompanyButtonMouseClicked
        if(addCompanyButton.isEnabled())
        {
            addCompany();
        }
    }//GEN-LAST:event_addCompanyButtonMouseClicked

    private void companyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyTableMouseClicked
       getSelectedRow();
    }//GEN-LAST:event_companyTableMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void searchCompanyFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCompanyFieldKeyReleased
        String txt = searchCompanyField.getText().toString();
        TableRowSorter trs = new TableRowSorter(companyTable.getModel());
        companyTable.setRowSorter(trs);       
        trs.setRowFilter(RowFilter.regexFilter("(?i)"+txt));
    }//GEN-LAST:event_searchCompanyFieldKeyReleased

    private void companyTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyTableMouseReleased
        if (evt.isPopupTrigger()) {
           DeletePopupMenu.show(companyTable, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_companyTableMouseReleased

    private void searchCompanyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCompanyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCompanyFieldActionPerformed

    private void deleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuActionPerformed
        deleteCompany();
    }//GEN-LAST:event_deleteMenuActionPerformed

    private void updateCompanyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCompanyButtonMouseClicked
        if(updateCompanyButton.isEnabled())
        {
            updateCompany();
        }        
    }//GEN-LAST:event_updateCompanyButtonMouseClicked

    private void contactPersonFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactPersonFieldKeyTyped
        char ch = evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch))
        {
            evt.consume();
        }
    }//GEN-LAST:event_contactPersonFieldKeyTyped

    private void clearFieldButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldButtonMouseClicked
        clearAllFields();
    }//GEN-LAST:event_clearFieldButtonMouseClicked

    private void companyNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companyNameFieldKeyReleased
        if(evt.getKeyCode()==9)
        {
            contactPersonField.requestFocus();
        }
    }//GEN-LAST:event_companyNameFieldKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(addCompanyButton.isEnabled()){
            addCompany();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(updateCompanyButton.isEnabled()){
            if(companyTable.getSelectedRow()>-1)
            {
                updateCompany();
            }else{
                new MessageForm("Error","Please select row to update.","error.png").setVisible(true);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(companyTable.getSelectedRow()>-1)
        {
            deleteCompany();
        }else{
            new MessageForm("Error","Please select row to delete.","error.png").setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        clearAllFields();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void companyTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companyTableKeyPressed
       
    }//GEN-LAST:event_companyTableKeyPressed

    private void companyTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companyTableKeyReleased
        if(evt.getKeyCode()==38 || evt.getKeyCode()==40)
        {
            getSelectedRow();
        }
        else if(evt.getKeyCode()==37)
        {
            companyNameField.requestFocusInWindow();
        }
    }//GEN-LAST:event_companyTableKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu DeletePopupMenu;
    private javax.swing.JLabel addCompanyButton;
    private javax.swing.JTextArea addressField;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel clearFieldButton;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JTable companyTable;
    private javax.swing.JTextField contactPersonField;
    private javax.swing.JMenuItem deleteMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrolPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchCompanyField;
    private javax.swing.JLabel updateCompanyButton;
    // End of variables declaration//GEN-END:variables

    private void populateCompanyTable() {
        ResultSet resultSet = new CompanyDAOImpl().viewAllCompanies();
        companyTable.setModel(DbUtils.resultSetToTableModel(resultSet));

        companyTable.getColumnModel().getColumn(0).setWidth(0);
        companyTable.getColumnModel().getColumn(0).setMinWidth(0);
        companyTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
      DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(11, 18, 29));
        headerRenderer.setForeground(new Color(140, 198, 62));

        for (int i = 0; i < companyTable.getModel().getColumnCount(); i++) {
            companyTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        companyTable.setShowHorizontalLines(true);
        companyTable.setShowVerticalLines(true);
        this.getContentPane().setBackground(Color.WHITE);
        jScrolPane.getViewport().setBackground(Color.WHITE);
    }

    private void clearAllFields() {
        companyNameField.setText("");
        contactPersonField.setText("");
        cityField.setText("");
        addressField.setText("");
        companyTable.clearSelection();
        disableButtons(1);
    }

    private void disableButtons(Integer i) {
        if(i==0)
        {
            addCompanyButton.setEnabled(false);
            updateCompanyButton.setEnabled(true);
        }else if(i==1){
            addCompanyButton.setEnabled(true);
            updateCompanyButton.setEnabled(false);
        }

    }

    private void updateCompany() {
        if(companyTable.getSelectedRow()>0)
        {
            Integer companyId = (Integer) companyTable.getValueAt(companyTable.getSelectedRow(), 0);
            if(companyNameField.getText().trim().equals("") || contactPersonField.getText().trim().equals("") || cityField.getText().trim().equals("") || addressField.getText().trim().equals(""))
            {
                new MessageForm("Error","Please fill all fields to update record.","error.png").setVisible(true);
            }else{
                CompanyModel companyModel = new CompanyModel();
                companyModel.setCompanyName(companyNameField.getText());
                companyModel.setContactPerson(contactPersonField.getText());
                companyModel.setCity(cityField.getText());
                companyModel.setAddress(addressField.getText());
                Timestamp currentTime = new Timestamp(System.currentTimeMillis());
                companyModel.setModifiedDate(currentTime);
                companyModel.setCompanyId(companyId);
                boolean check = new CompanyDAOImpl().updateCompany(companyModel);
                if(check)
                {
                    new MessageForm("Error", "Record could not be updated try again.","error.png").setVisible(true); 
                }else{
                    new MessageForm("Success", "Record has been updated.","info.png").setVisible(true);
                    clearAllFields();
                    populateCompanyTable();
                    disableButtons(1);
                }
            }
        }
    }

    private void addCompany() {
        if(companyNameField.getText().trim().equals("") || contactPersonField.getText().trim().equals("") || cityField.getText().trim().equals("") || addressField.getText().trim().equals(""))
        {
            new MessageForm("Error","Please fill all fileds to add record.","error.png").setVisible(true);
        }else{
            CompanyModel companyModel = new CompanyModel();
            companyModel.setCompanyName(companyNameField.getText());
            companyModel.setContactPerson(contactPersonField.getText());
            companyModel.setCity(cityField.getText());
            companyModel.setAddress(addressField.getText());
            Timestamp currentTime = new Timestamp(System.currentTimeMillis());
            companyModel.setCreatedDate(currentTime);
            companyModel.setModifiedDate(currentTime);
            boolean check = new CompanyDAOImpl().addCompany(companyModel);
            if(check)
            {
                new MessageForm("Error", "Record could not be added try again.","error.png").setVisible(true); 
            }else{
                new MessageForm("Success", "Record has been added.","info.png").setVisible(true);
                clearAllFields();
                populateCompanyTable();
            }
        }
    }

    private void deleteCompany() {
        if(companyTable.getSelectedRow()>0)
        {
            Integer companyId = (Integer) companyTable.getValueAt(companyTable.getSelectedRow(), 0);
            CompanyModel companyModel = new CompanyModel();
            companyModel.setCompanyId(companyId);
            Timestamp modifiedDate = new Timestamp(System.currentTimeMillis());
            companyModel.setModifiedDate(modifiedDate);
            boolean row = new CompanyDAOImpl().deleteCompanyById(companyModel);
            if (row) {
                new MessageForm("Error","Could not delete record,try again.","error.png").setVisible(true);
            } else {
                new MessageForm("Success","Record has been deleted successfully.","info.png").setVisible(true);
                populateCompanyTable();
                clearAllFields();
                disableButtons(1);
            }
        }
    }

    private void getSelectedRow() {
             Integer companyId = (Integer) companyTable.getValueAt(companyTable.getSelectedRow(), 0) ;
            CompanyModel companyModel = new CompanyDAOImpl().getCompanyById(companyId);
            companyNameField.setText(companyModel.getCompanyName());
            contactPersonField.setText(companyModel.getContactPerson());
            cityField.setText(companyModel.getCity());
            addressField.setText(companyModel.getAddress());
            disableButtons(0);
    }
}
