/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import daoimpl.RolePermissionDAOImpl;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import models.PermissionModel;

/**
 *
 * @author win8
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form F2
     */
    public Main() {

        //  frames[] = {new EmployeesFrame(),new RoleFrame(),new ProductFrame(),new StoreFrame(),new BankFrame(),new CompanyFrame(),new BrokerFrame(),new RolePermissionFrame(),new PurchaseFrame(),new SellFrame(),new SellDetailNewFrame(),new PurchaseDetailFrame(),new ShopStoreFrame(),new StoreStoreFrame(),new ProfitAndLossFrame() };
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        initComponents();
        //addMenu(); 

        userName.setText(LoginFrame.employeesModel.getUsername());
        userRole.setText(LoginFrame.employeesModel.getRoleModel().getRole());
        employees.setEnabled(false);
        brokerbtn.setEnabled(false);
        companybtn.setEnabled(false);
        bankbtn.setEnabled(false);
        productbtn.setEnabled(false);
        purchasebtn.setEnabled(false);
        purchasedetailbtn.setEnabled(false);
        sellbtn.setEnabled(false);
        selldetailbtn.setEnabled(false);
        selldetailbtn.setVisible(false);
        rolepermissionbtn.setEnabled(false);
        rolebtn.setEnabled(false);
        storebtn.setEnabled(false);
        storetoshopbtn.setEnabled(false);
        storetostrorebtn.setEnabled(false);
        profitlossbtn.setEnabled(false);
        checkPermissions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_Center = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane_Menu = new javax.swing.JScrollPane();
        jPanel_Menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        employees = new javax.swing.JLabel();
        brokerbtn = new javax.swing.JLabel();
        companybtn = new javax.swing.JLabel();
        bankbtn = new javax.swing.JLabel();
        productbtn = new javax.swing.JLabel();
        purchasebtn = new javax.swing.JLabel();
        purchasedetailbtn = new javax.swing.JLabel();
        sellbtn = new javax.swing.JLabel();
        profitlossbtn = new javax.swing.JLabel();
        selldetailbtn = new javax.swing.JLabel();
        rolepermissionbtn = new javax.swing.JLabel();
        rolebtn = new javax.swing.JLabel();
        storebtn = new javax.swing.JLabel();
        storetoshopbtn = new javax.swing.JLabel();
        storetostrorebtn = new javax.swing.JLabel();
        jPanel_UP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userRole = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jPanel_Down = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airbnb");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 600));

        jPanel_Center.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel6.setBackground(new java.awt.Color(47, 55, 67));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Leet Solutions");
        jLabel6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 750;
        gridBagConstraints.ipady = 500;
        jPanel2.add(jLabel6, gridBagConstraints);

        jPanel_Center.add(jPanel2, java.awt.BorderLayout.CENTER);

        jScrollPane_Menu.setBorder(null);
        jScrollPane_Menu.setPreferredSize(new java.awt.Dimension(278, 2));

        jPanel_Menu.setBackground(new java.awt.Color(11, 18, 29));
        jPanel_Menu.setMaximumSize(new java.awt.Dimension(280, 768));
        jPanel_Menu.setPreferredSize(new java.awt.Dimension(280, 920));
        jPanel_Menu.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(140, 198, 62));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("M E N U");
        jLabel3.setMaximumSize(new java.awt.Dimension(280, 90));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(280, 90));
        jPanel_Menu.add(jLabel3);
        jLabel3.setBounds(0, 0, 280, 90);

        employees.setBackground(new java.awt.Color(11, 18, 29));
        employees.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        employees.setForeground(new java.awt.Color(255, 255, 255));
        employees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employees.setText("Employees");
        employees.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        employees.setOpaque(true);
        employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeesMouseExited(evt);
            }
        });
        jPanel_Menu.add(employees);
        employees.setBounds(0, 90, 260, 50);

        brokerbtn.setBackground(new java.awt.Color(11, 18, 29));
        brokerbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        brokerbtn.setForeground(new java.awt.Color(255, 255, 255));
        brokerbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brokerbtn.setText("Broker");
        brokerbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        brokerbtn.setOpaque(true);
        brokerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brokerbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brokerbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brokerbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(brokerbtn);
        brokerbtn.setBounds(0, 140, 260, 50);

        companybtn.setBackground(new java.awt.Color(11, 18, 29));
        companybtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        companybtn.setForeground(new java.awt.Color(255, 255, 255));
        companybtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companybtn.setText("Company");
        companybtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        companybtn.setOpaque(true);
        companybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companybtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                companybtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                companybtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(companybtn);
        companybtn.setBounds(0, 190, 260, 50);

        bankbtn.setBackground(new java.awt.Color(11, 18, 29));
        bankbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        bankbtn.setForeground(new java.awt.Color(255, 255, 255));
        bankbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankbtn.setText("Bank");
        bankbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        bankbtn.setOpaque(true);
        bankbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bankbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bankbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bankbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(bankbtn);
        bankbtn.setBounds(0, 240, 260, 50);

        productbtn.setBackground(new java.awt.Color(11, 18, 29));
        productbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        productbtn.setForeground(new java.awt.Color(255, 255, 255));
        productbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productbtn.setText("Product");
        productbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        productbtn.setOpaque(true);
        productbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(productbtn);
        productbtn.setBounds(0, 290, 260, 50);

        purchasebtn.setBackground(new java.awt.Color(11, 18, 29));
        purchasebtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        purchasebtn.setForeground(new java.awt.Color(255, 255, 255));
        purchasebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchasebtn.setText("Purchase");
        purchasebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        purchasebtn.setOpaque(true);
        purchasebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchasebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchasebtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(purchasebtn);
        purchasebtn.setBounds(0, 340, 260, 50);

        purchasedetailbtn.setBackground(new java.awt.Color(11, 18, 29));
        purchasedetailbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        purchasedetailbtn.setForeground(new java.awt.Color(255, 255, 255));
        purchasedetailbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchasedetailbtn.setText("Purchase Detail");
        purchasedetailbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        purchasedetailbtn.setOpaque(true);
        purchasedetailbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasedetailbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchasedetailbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchasedetailbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(purchasedetailbtn);
        purchasedetailbtn.setBounds(0, 390, 260, 60);

        sellbtn.setBackground(new java.awt.Color(11, 18, 29));
        sellbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        sellbtn.setForeground(new java.awt.Color(255, 255, 255));
        sellbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sellbtn.setText("Sell");
        sellbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        sellbtn.setOpaque(true);
        sellbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sellbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sellbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(sellbtn);
        sellbtn.setBounds(0, 450, 260, 50);

        profitlossbtn.setBackground(new java.awt.Color(11, 18, 29));
        profitlossbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        profitlossbtn.setForeground(new java.awt.Color(255, 255, 255));
        profitlossbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profitlossbtn.setText("Profit Loss");
        profitlossbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        profitlossbtn.setOpaque(true);
        profitlossbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profitlossbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profitlossbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profitlossbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(profitlossbtn);
        profitlossbtn.setBounds(0, 850, 260, 60);

        selldetailbtn.setBackground(new java.awt.Color(11, 18, 29));
        selldetailbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        selldetailbtn.setForeground(new java.awt.Color(255, 255, 255));
        selldetailbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selldetailbtn.setText("Sell Detail");
        selldetailbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        selldetailbtn.setOpaque(true);
        selldetailbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selldetailbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selldetailbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selldetailbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(selldetailbtn);
        selldetailbtn.setBounds(0, 500, 260, 60);

        rolepermissionbtn.setBackground(new java.awt.Color(11, 18, 29));
        rolepermissionbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        rolepermissionbtn.setForeground(new java.awt.Color(255, 255, 255));
        rolepermissionbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rolepermissionbtn.setText("Role Permission");
        rolepermissionbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        rolepermissionbtn.setOpaque(true);
        rolepermissionbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rolepermissionbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rolepermissionbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rolepermissionbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(rolepermissionbtn);
        rolepermissionbtn.setBounds(0, 560, 260, 60);

        rolebtn.setBackground(new java.awt.Color(11, 18, 29));
        rolebtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        rolebtn.setForeground(new java.awt.Color(255, 255, 255));
        rolebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rolebtn.setText("Role ");
        rolebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        rolebtn.setOpaque(true);
        rolebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rolebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rolebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rolebtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(rolebtn);
        rolebtn.setBounds(0, 620, 260, 50);

        storebtn.setBackground(new java.awt.Color(11, 18, 29));
        storebtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        storebtn.setForeground(new java.awt.Color(255, 255, 255));
        storebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storebtn.setText("Store");
        storebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        storebtn.setOpaque(true);
        storebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                storebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                storebtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(storebtn);
        storebtn.setBounds(0, 670, 260, 60);

        storetoshopbtn.setBackground(new java.awt.Color(11, 18, 29));
        storetoshopbtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        storetoshopbtn.setForeground(new java.awt.Color(255, 255, 255));
        storetoshopbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storetoshopbtn.setText("Store To Shop");
        storetoshopbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        storetoshopbtn.setOpaque(true);
        storetoshopbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storetoshopbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                storetoshopbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                storetoshopbtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(storetoshopbtn);
        storetoshopbtn.setBounds(0, 730, 260, 60);

        storetostrorebtn.setBackground(new java.awt.Color(11, 18, 29));
        storetostrorebtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        storetostrorebtn.setForeground(new java.awt.Color(255, 255, 255));
        storetostrorebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storetostrorebtn.setText("Store To Store");
        storetostrorebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 55, 67)));
        storetostrorebtn.setOpaque(true);
        storetostrorebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storetostrorebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                storetostrorebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                storetostrorebtnMouseExited(evt);
            }
        });
        jPanel_Menu.add(storetostrorebtn);
        storetostrorebtn.setBounds(0, 790, 260, 60);

        jScrollPane_Menu.setViewportView(jPanel_Menu);

        jPanel_Center.add(jScrollPane_Menu, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel_Center, java.awt.BorderLayout.CENTER);

        jPanel_UP.setBackground(new java.awt.Color(11, 18, 29));
        jPanel_UP.setPreferredSize(new java.awt.Dimension(10, 150));
        jPanel_UP.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(140, 198, 62));
        jLabel4.setText("Rice Inventory Management");
        jPanel_UP.add(jLabel4);
        jLabel4.setBounds(470, 60, 340, 31);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(140, 198, 62));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel_UP.add(jLabel5);
        jLabel5.setBounds(1300, 100, 60, 50);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logout");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel_UP.add(jLabel1);
        jLabel1.setBounds(1290, 10, 60, 30);

        userRole.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        userRole.setForeground(new java.awt.Color(255, 255, 255));
        userRole.setText("jLabel7");
        jPanel_UP.add(userRole);
        userRole.setBounds(1130, 10, 140, 30);

        userName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("jLabel7");
        jPanel_UP.add(userName);
        userName.setBounds(1000, 10, 110, 30);

        getContentPane().add(jPanel_UP, java.awt.BorderLayout.PAGE_START);

        jPanel_Down.setBackground(new java.awt.Color(140, 198, 62));
        jPanel_Down.setPreferredSize(new java.awt.Dimension(10, 40));
        jPanel_Down.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© 2017 Leet Solutions | All Right Reserved ");
        jPanel_Down.add(jLabel2, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel_Down, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void employeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseEntered
        employees.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_employeesMouseEntered

    private void employeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseExited
        employees.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_employeesMouseExited

    private void brokerbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brokerbtnMouseEntered
        brokerbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_brokerbtnMouseEntered

    private void brokerbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brokerbtnMouseExited
        brokerbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_brokerbtnMouseExited

    private void companybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companybtnMouseEntered
        companybtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_companybtnMouseEntered

    private void companybtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companybtnMouseExited
        companybtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_companybtnMouseExited

    private void bankbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankbtnMouseEntered
        bankbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_bankbtnMouseEntered

    private void bankbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankbtnMouseExited
        bankbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_bankbtnMouseExited

    private void productbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productbtnMouseEntered
        productbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_productbtnMouseEntered

    private void productbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productbtnMouseExited
        productbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_productbtnMouseExited

    private void purchasebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasebtnMouseEntered
        purchasebtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_purchasebtnMouseEntered

    private void purchasebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasebtnMouseExited
        purchasebtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_purchasebtnMouseExited

    private void purchasedetailbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedetailbtnMouseEntered
        purchasedetailbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_purchasedetailbtnMouseEntered

    private void purchasedetailbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedetailbtnMouseExited
        purchasedetailbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_purchasedetailbtnMouseExited

    private void sellbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellbtnMouseEntered
        sellbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_sellbtnMouseEntered

    private void sellbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellbtnMouseExited
        sellbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_sellbtnMouseExited

    private void rolepermissionbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolepermissionbtnMouseEntered
        rolepermissionbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_rolepermissionbtnMouseEntered

    private void rolepermissionbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolepermissionbtnMouseExited
        rolepermissionbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_rolepermissionbtnMouseExited

    private void rolebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolebtnMouseEntered
        rolebtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_rolebtnMouseEntered

    private void rolebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolebtnMouseExited
        rolebtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_rolebtnMouseExited

    private void storebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storebtnMouseEntered
        storebtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_storebtnMouseEntered

    private void storebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storebtnMouseExited
        storebtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_storebtnMouseExited

    private void storetoshopbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storetoshopbtnMouseEntered
        storetoshopbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_storetoshopbtnMouseEntered

    private void storetoshopbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storetoshopbtnMouseExited
        storetoshopbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_storetoshopbtnMouseExited

    private void storetostrorebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storetostrorebtnMouseEntered
        storetostrorebtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_storetostrorebtnMouseEntered

    private void storetostrorebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storetostrorebtnMouseExited
        storetostrorebtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_storetostrorebtnMouseExited

    private void profitlossbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profitlossbtnMouseEntered
        profitlossbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_profitlossbtnMouseEntered

    private void profitlossbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profitlossbtnMouseExited
        profitlossbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_profitlossbtnMouseExited

    private void employeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseClicked
        if (!employees.isEnabled()) {
            return;
        } else {
            new EmployeesFrame().setVisible(true);
        }
    }//GEN-LAST:event_employeesMouseClicked

    private void brokerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brokerbtnMouseClicked
        if (!brokerbtn.isEnabled()) {
            return;
        } else {
            new BrokerFrame().setVisible(true);
        }
    }//GEN-LAST:event_brokerbtnMouseClicked

    private void companybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companybtnMouseClicked
        if (!companybtn.isEnabled()) {
            return;
        } else {
            new CompanyFrame().setVisible(true);
        }
    }//GEN-LAST:event_companybtnMouseClicked

    private void bankbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankbtnMouseClicked
        if (!bankbtn.isEnabled()) {
            return;
        } else {
            new BankFrame().setVisible(true);
        }
    }//GEN-LAST:event_bankbtnMouseClicked

    private void productbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productbtnMouseClicked
        if (!productbtn.isEnabled()) {
            return;
        } else {
            new ProductFrame().setVisible(true);
        }
    }//GEN-LAST:event_productbtnMouseClicked

    private void purchasebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasebtnMouseClicked
        if (!purchasebtn.isEnabled()) {
            return;
        } else {
            new PurchaseFrame().setVisible(true);
        }
    }//GEN-LAST:event_purchasebtnMouseClicked

    private void purchasedetailbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedetailbtnMouseClicked
        if (!purchasedetailbtn.isEnabled()) {
            return;
        } else {
            new PurchaseDetailFrame().setVisible(true);
        }
    }//GEN-LAST:event_purchasedetailbtnMouseClicked

    private void sellbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellbtnMouseClicked

        if (!sellbtn.isEnabled()) {
            return;
        } else {
            new SellFrame().setVisible(true);
        }
    }//GEN-LAST:event_sellbtnMouseClicked

    private void rolepermissionbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolepermissionbtnMouseClicked
        if (!rolepermissionbtn.isEnabled()) {
            return;
        } else {
            new RolePermissionFrame().setVisible(true);
        }
    }//GEN-LAST:event_rolepermissionbtnMouseClicked

    private void rolebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolebtnMouseClicked
        if (!rolebtn.isEnabled()) {
            return;
        } else {
            new RoleFrame().setVisible(true);
        }
    }//GEN-LAST:event_rolebtnMouseClicked

    private void storebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storebtnMouseClicked
        if (!storebtn.isEnabled()) {
            return;
        } else {
            new StoreFrame().setVisible(true);
        }
    }//GEN-LAST:event_storebtnMouseClicked

    private void storetoshopbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storetoshopbtnMouseClicked
        if (!storetoshopbtn.isEnabled()) {
            return;
        } else {
            new ShopStoreFrame().setVisible(true);
        }
    }//GEN-LAST:event_storetoshopbtnMouseClicked

    private void storetostrorebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storetostrorebtnMouseClicked
        if (!storetostrorebtn.isEnabled()) {
            return;
        } else {
            new StoreStoreFrame().setVisible(true);
        }
    }//GEN-LAST:event_storetostrorebtnMouseClicked

    private void profitlossbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profitlossbtnMouseClicked
        if (!profitlossbtn.isEnabled()) {
            return;
        } else {
            new ProfitAndLossFrame().setVisible(true);
        }
    }//GEN-LAST:event_profitlossbtnMouseClicked

    private void selldetailbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selldetailbtnMouseExited
        selldetailbtn.setBackground(new java.awt.Color(11, 18, 29));
    }//GEN-LAST:event_selldetailbtnMouseExited

    private void selldetailbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selldetailbtnMouseEntered
        selldetailbtn.setBackground(new java.awt.Color(47, 55, 67));
    }//GEN-LAST:event_selldetailbtnMouseEntered

    private void selldetailbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selldetailbtnMouseClicked
        if (!selldetailbtn.isEnabled()) {
            return;
        } else {
            new SellDetailNewFrame().setVisible(true);
        }
    }//GEN-LAST:event_selldetailbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new Main().setVisible(true);
            }
        });

    }

    private void checkPermissions() {
        ResultSet assignedPermissions = new RolePermissionDAOImpl().getAssignedPermissions(LoginFrame.employeesModel.getRoleModel().getRole());
        ArrayList<PermissionModel> permissionList = new ArrayList<>();

        try {
            while (assignedPermissions.next()) {
                PermissionModel permissionModel = new PermissionModel();
                permissionModel.setPermission(assignedPermissions.getString("Permission"));
                permissionList.add(permissionModel);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

        for (PermissionModel permissionModel : permissionList) {

            if (permissionModel.getPermission().equals("View_Employee")) {
                employees.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_Bank")) {
                bankbtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_Role")) {
                rolebtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_Product")) {
                productbtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_Store")) {
                storebtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_Company")) {
                companybtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_Broker")) {

                brokerbtn.setEnabled(true);

            }
            if (permissionModel.getPermission().equals("View_Role_Permission")) {
                rolepermissionbtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_Purchase")) {
                purchasebtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_Sell")) {
                sellbtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_PurchaseDetail")) {

                purchasedetailbtn.setEnabled(true);

            }
            if (permissionModel.getPermission().equals("View_ShopStore")) {

                storetoshopbtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_StoreStore")) {

                storetostrorebtn.setEnabled(true);
            }
            if (permissionModel.getPermission().equals("View_ProfitAndLoss")) {

                profitlossbtn.setEnabled(true);

            }

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankbtn;
    private javax.swing.JLabel brokerbtn;
    private javax.swing.JLabel companybtn;
    private javax.swing.JLabel employees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Center;
    private javax.swing.JPanel jPanel_Down;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_UP;
    private javax.swing.JScrollPane jScrollPane_Menu;
    private javax.swing.JLabel productbtn;
    private javax.swing.JLabel profitlossbtn;
    private javax.swing.JLabel purchasebtn;
    private javax.swing.JLabel purchasedetailbtn;
    private javax.swing.JLabel rolebtn;
    private javax.swing.JLabel rolepermissionbtn;
    private javax.swing.JLabel sellbtn;
    private javax.swing.JLabel selldetailbtn;
    private javax.swing.JLabel storebtn;
    private javax.swing.JLabel storetoshopbtn;
    private javax.swing.JLabel storetostrorebtn;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userRole;
    // End of variables declaration//GEN-END:variables

}
