/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import daoimpl.ProductDaoImpl;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import models.ProductModel;
/**
 *
 * @author Intel
 */
public class ProductFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProductFrame
     */
    ProductDaoImpl productDaoImpl = null;
    public ProductFrame() {
        productDaoImpl = new ProductDaoImpl();
        initComponents();
        this.setLocationRelativeTo(null);
        fillProductTableData();
        clearFields();
    }

    public void fillProductTableData(){
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row , int column){
                return false;
            }
        };
        
        dtm = (DefaultTableModel) DbUtils.resultSetToTableModel(productDaoImpl.getAllProducts());
        
        tblproductTable.setModel(dtm);
        
        tblproductTable.getColumnModel().getColumn(0).setWidth(0);
        tblproductTable.getColumnModel().getColumn(0).setMinWidth(0);
        tblproductTable.getColumnModel().getColumn(0).setMaxWidth(0);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(11, 18, 29));
        headerRenderer.setForeground(new Color(140, 198, 62));

        for (int i = 0; i < tblproductTable.getModel().getColumnCount(); i++) {
            tblproductTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        tblproductTable.setShowHorizontalLines(true);
        tblproductTable.setShowVerticalLines(true);
        this.getContentPane().setBackground(Color.WHITE);
        jScrollPane2.getViewport().setBackground(Color.WHITE);
        
     }
    
    private void clearFields(){
        txtproductName.setText("");
        txtproductSearch.setText("");
        btnAddProduct.setEnabled(true);
        btnUpdateProduct.setEnabled(false);
        tblproductTable.clearSelection();
    }
    
    private void deleteProduct(int productId){
        int re = productDaoImpl.deleteProduct(productId);
        if(re>0){
            new MessageForm("Success", "Product Deleted", "info.png").setVisible(true);
            clearFields();
            fillProductTableData();
        }
        else{
            new MessageForm("Error", "Error Occured", "error.png").setVisible(true);
            
        }    
    }
    
    private void updateProduct(int id){
        ProductModel productModel = new ProductModel();
       
        productModel.setProductId(id);
        productModel.setProductName(txtproductName.getText());
        productModel.setModifiedBy(LoginFrame.employeesModel);
        int re = productDaoImpl.updateProduct(productModel);
        if(re>0){
            new MessageForm("Success", "Product Updated", "info.png").setVisible(true);
            clearFields();
            fillProductTableData();
        }
        else{
            new MessageForm("Error", "Error Occured", "error.png").setVisible(true);
            
        }
    }
    
    private void addProduct(){
        String productName = txtproductName.getText();
        if(productName.trim().equals("")){
            new MessageForm("Error", "Product Name Required", "error.png").setVisible(true);
            return;
        }
        else if(productDaoImpl.checkProductBeforeInsertion(productName)){
            new MessageForm("Error", "Product Already Existed", "error.png").setVisible(true);
        }
        else{
            ProductModel productModel = new ProductModel();
            productModel.setProductName(txtproductName.getText());
            productModel.setCreatedBy(LoginFrame.employeesModel);
            int re = productDaoImpl.insertNewProduct(productModel);
            if(re>0){
                new MessageForm("Success", "Product ADDED", "info.png").setVisible(true);
                clearFields();
                fillProductTableData();
            }
            else{
                new MessageForm("Error", "Error Occured", "error.png").setVisible(true);
            
            }
        }
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        deleteProduct = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtproductSearch = new javax.swing.JTextField();
        txtproductName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblproductTable = new javax.swing.JTable();
        btnAddProduct = new javax.swing.JLabel();
        btnUpdateProduct = new javax.swing.JLabel();
        lblReset = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        deleteProduct.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        deleteProduct.setText("Delete Employee");
        deleteProduct.setActionCommand("Delete Product");
        deleteProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductActionPerformed(evt);
            }
        });
        jPopupMenu1.add(deleteProduct);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 78, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search Products");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 26));

        txtproductSearch.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtproductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductSearchActionPerformed(evt);
            }
        });
        txtproductSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtproductSearchKeyReleased(evt);
            }
        });
        jPanel2.add(txtproductSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 220, -1));

        txtproductName.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtproductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtproductNameKeyReleased(evt);
            }
        });
        jPanel2.add(txtproductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 75, 188, -1));

        tblproductTable.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        tblproductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblproductTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblproductTable.setRowHeight(20);
        tblproductTable.setSelectionBackground(new java.awt.Color(11, 18, 29));
        tblproductTable.setSelectionForeground(new java.awt.Color(140, 198, 62));
        tblproductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblproductTableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblproductTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 75, 560, 390));

        btnAddProduct.setBackground(new java.awt.Color(140, 198, 62));
        btnAddProduct.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddProduct.setText("Add Product");
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.setOpaque(true);
        btnAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProductMouseClicked(evt);
            }
        });
        jPanel2.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 138, 34));

        btnUpdateProduct.setBackground(new java.awt.Color(140, 198, 62));
        btnUpdateProduct.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnUpdateProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateProduct.setOpaque(true);
        btnUpdateProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateProductMouseClicked(evt);
            }
        });
        jPanel2.add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 34));

        lblReset.setBackground(new java.awt.Color(140, 198, 62));
        lblReset.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lblReset.setForeground(new java.awt.Color(255, 255, 255));
        lblReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReset.setText("Reset");
        lblReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReset.setOpaque(true);
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
        });
        jPanel2.add(lblReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 300, 30));

        jPanel1.setBackground(new java.awt.Color(11, 18, 29));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 192, 62));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Products Panel");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtproductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductSearchActionPerformed

    private void txtproductSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductSearchKeyReleased
        String productNameSearch = txtproductSearch.getText();
        TableRowSorter tableRowSorter = new TableRowSorter(tblproductTable.getModel());
        tblproductTable.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + productNameSearch));        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductSearchKeyReleased

    private void tblproductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductTableMouseClicked
        btnAddProduct.setEnabled(false);
        btnUpdateProduct.setEnabled(true);
        int selectedRow = tblproductTable.getSelectedRow();

        if (selectedRow > -1) {
            String name = (String) tblproductTable.getValueAt(tblproductTable.getSelectedRow(), 1);
            
            txtproductName.setText(name);
            
        }

    }//GEN-LAST:event_tblproductTableMouseClicked

    private void tblproductTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductTableMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(tblproductTable, evt.getX(), evt.getY());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblproductTableMouseReleased

    private void btnAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseClicked
               // TODO add your handling code here:
               addProduct();
    }//GEN-LAST:event_btnAddProductMouseClicked

    private void btnUpdateProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateProductMouseClicked
        Integer row = tblproductTable.getSelectedRow();

        if (row > -1) {
            Integer id = (Integer) tblproductTable.getValueAt(tblproductTable.getSelectedRow(), 0);
            updateProduct(id);
        } else {
            new MessageForm("Error", "Please select row", "error.png").setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateProductMouseClicked

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        //clearFields();
        tblproductTable.clearSelection();
        btnAddProduct.setEnabled(true);
        btnUpdateProduct.setEnabled(false);
    }//GEN-LAST:event_lblResetMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        tblproductTable.clearSelection();
        btnAddProduct.setEnabled(true);
        btnUpdateProduct.setEnabled(false);
        //clearFields();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductActionPerformed
        Integer row = tblproductTable.getSelectedRow();

        if (row > -1) {
            Integer id = (Integer) tblproductTable.getValueAt(tblproductTable.getSelectedRow(), 0);
            deleteProduct(id);
        } else {
            new MessageForm("Error", "Please select row", "error.png").setVisible(true);
        }
    }//GEN-LAST:event_deleteProductActionPerformed

    private void txtproductNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductNameKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            addProduct();
        }
    }//GEN-LAST:event_txtproductNameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddProduct;
    private javax.swing.JLabel btnUpdateProduct;
    private javax.swing.JMenuItem deleteProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblReset;
    private javax.swing.JTable tblproductTable;
    private javax.swing.JTextField txtproductName;
    private javax.swing.JTextField txtproductSearch;
    // End of variables declaration//GEN-END:variables
}
