/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import daoimpl.BankDaoImpl;
import daoimpl.PurchaseExpenseDaoImpl;
import daoimpl.SellExpenseDaoImpl;
import java.awt.Color;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.BrokerModel;
import models.CompanyModel;
import models.EmployeesModel;
import models.PurchaseModel;
import utility.CommonMethods;
import models.BankModel;
import java.awt.Dimension;
import javax.swing.UIManager;
import models.PurchaseExpenseModel;
import models.SellModel;

/**
 *
 * @author Intel
 */
public class SellExpenses extends javax.swing.JFrame {

    SellExpenseDaoImpl sellExpenseDaoImpl;
    BankDaoImpl bankDaoImpl;
    SellFrame sellFrame;
    SellModel sellModel;
    BankModel bankModel;
    PurchaseExpenseModel purchaseExpenseModel;

    /**
     * Creates new form PurchaseFrame
     */
    public SellExpenses(int sellId, SellFrame sellFrame) {
        initComponents();
        sellModel = new SellModel();
        sellModel.setSellId(sellId);
        bankDaoImpl = new BankDaoImpl();
        bankModel = new BankModel();
        sellExpenseDaoImpl = new SellExpenseDaoImpl();
        purchaseExpenseModel = new PurchaseExpenseModel();
        this.setExtendedState(MAXIMIZED_BOTH);
        accNo.setEditable(false);
        accTitle.setEditable(false);
        CommonMethods.fillTables(bankDaoImpl.getAllAccounts(), bankTable, jScrollPane3, this);
        CommonMethods.fillTables(sellExpenseDaoImpl.getAllPurchaseExpense(sellModel), tblPurchase, jScrollPane2, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        deletePurchase = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bankTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfSearchPurchase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        addExpense = new javax.swing.JLabel();
        lblResetPurchase = new javax.swing.JLabel();
        transport = new javax.swing.JTextField();
        comboPaymentType = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();
        accNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        accTitle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        labour = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        other = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        brokerComission = new javax.swing.JTextField();
        brokerPaid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        deletePurchase.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        deletePurchase.setText("Delete Expense");
        deletePurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePurchaseActionPerformed(evt);
            }
        });
        jPopupMenu1.add(deletePurchase);

        jDialog1.setUndecorated(true);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(11, 18, 29));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(140, 198, 62));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bank");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        bankTable.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        bankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bankTable.setRowHeight(20);
        bankTable.setSelectionBackground(new java.awt.Color(11, 18, 29));
        bankTable.setSelectionForeground(new java.awt.Color(140, 198, 62));
        bankTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bankTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(bankTable);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 670, 240));

        jDialog1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 320));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Note :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search Expense");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, -1, 26));

        tfSearchPurchase.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfSearchPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchPurchaseActionPerformed(evt);
            }
        });
        tfSearchPurchase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchPurchaseKeyReleased(evt);
            }
        });
        jPanel2.add(tfSearchPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, 220, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Payment Type :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        tblPurchase.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblPurchase.setRowHeight(20);
        tblPurchase.setSelectionBackground(new java.awt.Color(11, 18, 29));
        tblPurchase.setSelectionForeground(new java.awt.Color(140, 198, 62));
        tblPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPurchaseMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPurchaseMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblPurchase);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 870, 510));

        addExpense.setBackground(new java.awt.Color(140, 198, 62));
        addExpense.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        addExpense.setForeground(new java.awt.Color(255, 255, 255));
        addExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addExpense.setText("Add Expense");
        addExpense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addExpense.setOpaque(true);
        addExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addExpenseMouseClicked(evt);
            }
        });
        jPanel2.add(addExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 390, 34));

        lblResetPurchase.setBackground(new java.awt.Color(140, 198, 62));
        lblResetPurchase.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lblResetPurchase.setForeground(new java.awt.Color(255, 255, 255));
        lblResetPurchase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResetPurchase.setText("Reset");
        lblResetPurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblResetPurchase.setOpaque(true);
        lblResetPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetPurchaseMouseClicked(evt);
            }
        });
        jPanel2.add(lblResetPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 390, 30));

        transport.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        transport.setText("0");
        transport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportActionPerformed(evt);
            }
        });
        transport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                transportKeyTyped(evt);
            }
        });
        jPanel2.add(transport, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 220, -1));

        comboPaymentType.setBackground(new java.awt.Color(204, 204, 255));
        comboPaymentType.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        comboPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Type", "Online", "Cheque", "Cash" }));
        comboPaymentType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPaymentTypeItemStateChanged(evt);
            }
        });
        comboPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaymentTypeActionPerformed(evt);
            }
        });
        jPanel2.add(comboPaymentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 220, 30));

        jPanel1.setBackground(new java.awt.Color(11, 18, 29));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 192, 62));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sell Expense");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(601, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(561, 561, 561)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 70));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Transport :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        note.setColumns(20);
        note.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        note.setRows(5);
        jScrollPane1.setViewportView(note);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 220, 100));

        accNo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel2.add(accNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Acc No :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        accTitle.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel2.add(accTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 220, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Acc Title :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        labour.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labour.setText("0");
        labour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                labourKeyTyped(evt);
            }
        });
        jPanel2.add(labour, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 220, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Labour :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Other :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        other.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        other.setText("0");
        other.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otherKeyTyped(evt);
            }
        });
        jPanel2.add(other, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 220, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Broker Comission :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));

        brokerComission.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        brokerComission.setText("0");
        brokerComission.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                brokerComissionKeyTyped(evt);
            }
        });
        jPanel2.add(brokerComission, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 220, -1));

        brokerPaid.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        brokerPaid.setText("0");
        brokerPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                brokerPaidKeyTyped(evt);
            }
        });
        jPanel2.add(brokerPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 220, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setText("Broker Paid  :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 30));

        jMenuBar1.setBackground(new java.awt.Color(11, 18, 29));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Update");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Delete");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Reset");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Back");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchPurchaseActionPerformed

    private void tfSearchPurchaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchPurchaseKeyReleased
        CommonMethods.searchFromTable(tblPurchase, tfSearchPurchase);

    }//GEN-LAST:event_tfSearchPurchaseKeyReleased

    private void tblPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPurchaseMouseClicked
        int row = tblPurchase.getSelectedRow();
    }//GEN-LAST:event_tblPurchaseMouseClicked

    private void tblPurchaseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPurchaseMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(tblPurchase, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblPurchaseMouseReleased

    private void addExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExpenseMouseClicked
        if (comboPaymentType.getSelectedItem().toString().equals("Online") || comboPaymentType.getSelectedItem().toString().equals("Cheque")) {
            if (!transport.getText().equals("") && !labour.getText().equals("") && !other.getText().equals("") && !brokerComission.getText().equals("") && !brokerPaid.getText().equals("") && !accNo.getText().equals("") && !accTitle.getText().equals("")) {
                purchaseExpenseModel.setTransportExpense(Integer.parseInt(transport.getText()));
                purchaseExpenseModel.setLabourExpense(Integer.parseInt(labour.getText()));
                purchaseExpenseModel.setOther(Integer.parseInt(other.getText()));
                purchaseExpenseModel.setBrokerComission(Integer.parseInt(brokerComission.getText()));
                purchaseExpenseModel.setBrokerPaidAmount(Integer.parseInt(brokerPaid.getText()));
                purchaseExpenseModel.setComment(note.getText());
                purchaseExpenseModel.setBank(bankModel);
                purchaseExpenseModel.setSellModel(sellModel);
                purchaseExpenseModel.setPaymentType(comboPaymentType.getSelectedItem().toString());
                purchaseExpenseModel.setCreatedBy(LoginFrame.employeesModel);

                int status = sellExpenseDaoImpl.insertPurchaseExpense(purchaseExpenseModel);
                if (status == 1) {
                    CommonMethods.fillTables(sellExpenseDaoImpl.getAllPurchaseExpense(sellModel), tblPurchase, jScrollPane2, this);
                }
            }
        } else if (comboPaymentType.getSelectedItem().toString().equals("Cash")) {
            if (!transport.getText().equals("") && !labour.getText().equals("") && !other.getText().equals("") && !brokerComission.getText().equals("") && !brokerPaid.getText().equals("")) {
                purchaseExpenseModel.setTransportExpense(Integer.parseInt(transport.getText()));
                purchaseExpenseModel.setLabourExpense(Integer.parseInt(labour.getText()));
                purchaseExpenseModel.setOther(Integer.parseInt(other.getText()));
                purchaseExpenseModel.setBrokerComission(Integer.parseInt(brokerComission.getText()));
                purchaseExpenseModel.setBrokerPaidAmount(Integer.parseInt(brokerPaid.getText()));
                purchaseExpenseModel.setComment(note.getText());
                purchaseExpenseModel.setSellModel(sellModel);
                purchaseExpenseModel.setPaymentType(comboPaymentType.getSelectedItem().toString());
                purchaseExpenseModel.setCreatedBy(LoginFrame.employeesModel);

                int status = sellExpenseDaoImpl.insertPurchaseExpenseWithoutBank(purchaseExpenseModel);
                if (status == 1) {
                    CommonMethods.fillTables(sellExpenseDaoImpl.getAllPurchaseExpense(sellModel), tblPurchase, jScrollPane2, this);
                }
            }
        } else if (comboPaymentType.getSelectedItem().toString().equals("Select Payment Type") && accNo.getText().equals("") && accTitle.getText().equals("")) {
            new MessageForm("Error", "Please select payment method", "error.png").setVisible(true);
        }
    }//GEN-LAST:event_addExpenseMouseClicked

    private void lblResetPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetPurchaseMouseClicked

    }//GEN-LAST:event_lblResetPurchaseMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void deletePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePurchaseActionPerformed
        int row = tblPurchase.getSelectedRow();
        if (row > -1) {
            if (tblPurchase.getValueAt(row, 3).toString().equals("Online") || tblPurchase.getValueAt(row, 3).toString().equals("Cheque")) {
            int expenseId = (int) tblPurchase.getValueAt(row, 0);
            BankModel bankModel = new BankModel();
            bankModel.setAccountNo((String) tblPurchase.getValueAt(row, 2));
            purchaseExpenseModel.setExpenseId(expenseId);
            purchaseExpenseModel.setTransportExpense((Integer) tblPurchase.getValueAt(row, 4));
            purchaseExpenseModel.setLabourExpense((Integer) tblPurchase.getValueAt(row, 5));
            purchaseExpenseModel.setOther((Integer) tblPurchase.getValueAt(row, 6));
            purchaseExpenseModel.setBrokerPaidAmount((Integer) tblPurchase.getValueAt(row, 8));
            purchaseExpenseModel.setComment(note.getText());
            purchaseExpenseModel.setBank(bankModel);

            int status = sellExpenseDaoImpl.deletePurchaseExpense(purchaseExpenseModel);
            if (status == 1) {
                CommonMethods.fillTables(sellExpenseDaoImpl.getAllPurchaseExpense(sellModel), tblPurchase, jScrollPane2, this);
            }
        }
            else if(tblPurchase.getValueAt(row, 3).toString().equals("Cash")){
           
            int expenseId = (int) tblPurchase.getValueAt(row, 0);
            purchaseExpenseModel.setExpenseId(expenseId);
        
            int status = sellExpenseDaoImpl.deletePurchaseExpenseWithoutBank(purchaseExpenseModel);
            if (status == 1) {
                CommonMethods.fillTables(sellExpenseDaoImpl.getAllPurchaseExpense(sellModel), tblPurchase, jScrollPane2, this);
            } 
            }
        }
        else {
            new MessageForm("Error", "Please select the expense", "error.png").setVisible(true);
        }
    }//GEN-LAST:event_deletePurchaseActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void transportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transportKeyTyped
        char ch = evt.getKeyChar();

        if (Character.isLetter(ch) || Character.isWhitespace(ch)) {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_transportKeyTyped

    private void labourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labourKeyTyped
        char ch = evt.getKeyChar();

        if (Character.isLetter(ch) || Character.isWhitespace(ch)) {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_labourKeyTyped

    private void otherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherKeyTyped
        char ch = evt.getKeyChar();

        if (Character.isLetter(ch) || Character.isWhitespace(ch)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_otherKeyTyped

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jDialog1.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void comboPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaymentTypeActionPerformed

    private void comboPaymentTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPaymentTypeItemStateChanged
        if (!comboPaymentType.getSelectedItem().toString().equals("Cash") && !comboPaymentType.getSelectedItem().toString().equals("Select Payment Type")) {
            jDialog1.setSize(new Dimension(687, 320));
            jDialog1.setLocationRelativeTo(accTitle);
            jDialog1.setVisible(true);

        } else if (comboPaymentType.getSelectedItem().toString().equals("Cash") || comboPaymentType.getSelectedItem().toString().equals("Select Payment Type")) {
            accNo.setText("");
            accTitle.setText("");
        }
    }//GEN-LAST:event_comboPaymentTypeItemStateChanged

    private void bankTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankTableMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                int bankId = (int) bankTable.getValueAt(bankTable.getSelectedRow(), 0);
                bankModel.setBankId(bankId);
                accNo.setText((String) bankTable.getValueAt(bankTable.getSelectedRow(), 2));
                accTitle.setText((String) bankTable.getValueAt(bankTable.getSelectedRow(), 1));
                jDialog1.dispose();
            } catch (Exception e) {
                e.printStackTrace();
                new MessageForm("Error", "Please select bank", "info.png").setVisible(true);
            }
        }
    }//GEN-LAST:event_bankTableMouseClicked

    private void brokerComissionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brokerComissionKeyTyped
        char ch = evt.getKeyChar();

        if (Character.isLetter(ch) || Character.isWhitespace(ch)) {
            evt.consume();
        }
    }//GEN-LAST:event_brokerComissionKeyTyped

    private void brokerPaidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brokerPaidKeyTyped
        char ch = evt.getKeyChar();

        if (Character.isLetter(ch) || Character.isWhitespace(ch)) {
            evt.consume();
        }
    }//GEN-LAST:event_brokerPaidKeyTyped

    private void transportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNo;
    private javax.swing.JTextField accTitle;
    private javax.swing.JLabel addExpense;
    private javax.swing.JTable bankTable;
    private javax.swing.JTextField brokerComission;
    private javax.swing.JTextField brokerPaid;
    private javax.swing.JComboBox<String> comboPaymentType;
    private javax.swing.JMenuItem deletePurchase;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField labour;
    private javax.swing.JLabel lblResetPurchase;
    private javax.swing.JTextArea note;
    private javax.swing.JTextField other;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTextField tfSearchPurchase;
    private javax.swing.JTextField transport;
    // End of variables declaration//GEN-END:variables
}
