/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;


import daoimpl.ShopDaoImpl;
import java.sql.ResultSet;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import models.ShopModel;


import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asif Ali
 */
public class ShopFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShopFrame
     */
    public ShopFrame() {
        initComponents();
        fillShopTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpopup = new javax.swing.JPopupMenu();
        Delete = new javax.swing.JMenuItem();
        addshop = new javax.swing.JLabel();
        updateshop = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jshopname = new javax.swing.JTextField();
        jshopquantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jshoptable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jshopsearch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        Delete.setBackground(new java.awt.Color(140, 198, 62));
        Delete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.setOpaque(true);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jpopup.add(Delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addshop.setBackground(new java.awt.Color(140, 198, 62));
        addshop.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addshop.setForeground(new java.awt.Color(255, 255, 255));
        addshop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addshop.setText("Add Shop");
        addshop.setOpaque(true);
        addshop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addshopMouseClicked(evt);
            }
        });
        getContentPane().add(addshop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 130, 40));

        updateshop.setBackground(new java.awt.Color(140, 198, 62));
        updateshop.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        updateshop.setForeground(new java.awt.Color(255, 255, 255));
        updateshop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateshop.setText("Update Shop");
        updateshop.setOpaque(true);
        updateshop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateshopMouseClicked(evt);
            }
        });
        getContentPane().add(updateshop, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 120, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jshopname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jshopquantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Quantity");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Name");

        jshoptable.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        jshoptable.setForeground(new java.awt.Color(11, 18, 29));
        jshoptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jshoptable.setRowHeight(20);
        jshoptable.setSelectionBackground(new java.awt.Color(11, 18, 29));
        jshoptable.setSelectionForeground(new java.awt.Color(140, 198, 62));
        jshoptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jshoptableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jshoptableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jshoptable);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Search");

        jshopsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jshopsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jshopsearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jshopquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jshopname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jshopsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jshopname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jshopquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jshopsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jPanel1.setBackground(new java.awt.Color(11, 18, 29));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(140, 198, 62));
        jLabel5.setText("Shop Frame");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(320, 320, 320)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addshopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addshopMouseClicked
        
        if(jshopname.getText().equals("")||jshopquantity.getText().equals("")){
        
       new MessageForm("UnSuccuss","All Fields Are Required To Fill","error.png").setVisible(true);     
        }else{
        String shopName = jshopname.getText();
        String shopQuantity = jshopquantity.getText();
        Timestamp currentTime = new Timestamp(System.currentTimeMillis());
        ShopModel shopModel  = new ShopModel();
        shopModel.setName(shopName);
        shopModel.setShopQty(shopQuantity);
        shopModel.setCreatedDate(currentTime);
        shopModel.setModifiedDate(currentTime);
        shopModel.setModifiedBy(LoginFrame.employeesModel);
        shopModel.setCreatedBy(LoginFrame.employeesModel);
        
        ShopDaoImpl shopDaoImpl = new ShopDaoImpl();
        int row = shopDaoImpl.insertShopData(shopModel);
        if(row>0){
       new MessageForm("Succuss","Inserted","info.png").setVisible(true);
        fillShopTable();
        }else{
        new MessageForm("UnSuccess","Not Inserted","error.png").setVisible(true);
        }
        }
        
        
    }//GEN-LAST:event_addshopMouseClicked

    private void updateshopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateshopMouseClicked
        if(jshopname.getText().equals("")||jshopquantity.getText().equals("")){
        
       new MessageForm("UnSuccuss","All Fields Are Required To Fill","error.png").setVisible(true)   ;  
        }else{
        int id = Integer.parseInt(jshoptable.getValueAt(jshoptable.getSelectedRow(), 0).toString());
        
        String shopName = jshopname.getText();
        String shopQuantity = jshopquantity.getText();
        Timestamp currentTime = new Timestamp(System.currentTimeMillis());
        ShopModel shopModel  = new ShopModel();
        shopModel.setName(shopName);
        shopModel.setShopQty(shopQuantity);
        shopModel.setModifiedDate(currentTime);
        shopModel.setModifiedBy(LoginFrame.employeesModel);
        shopModel.setShopId(id);
        ShopDaoImpl shopDaoImpl = new ShopDaoImpl();
        int row = shopDaoImpl.updateShopData(shopModel);
        if(row>0){
        new MessageForm("Succuss","Updated","info.png").setVisible(true);
        fillShopTable();
        }else{
        new MessageForm("UnSuccuss","Not Updated","error.png").setVisible(true);
        
        }
        }
    }//GEN-LAST:event_updateshopMouseClicked

    private void jshoptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jshoptableMouseClicked
        jshopname.setText(jshoptable.getValueAt(jshoptable.getSelectedRow(), 1).toString());
        jshopquantity.setText(jshoptable.getValueAt(jshoptable.getSelectedRow(), 2).toString());
                

    }//GEN-LAST:event_jshoptableMouseClicked

    private void jshopsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jshopsearchKeyReleased
      String jshopSearch = jshopsearch.getText();
        TableRowSorter tableRowSorter = new TableRowSorter(jshoptable.getModel());
        jshoptable.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + jshopSearch));
    }//GEN-LAST:event_jshopsearchKeyReleased

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
      int id = Integer.parseInt(jshoptable.getValueAt(jshoptable.getSelectedRow(),0 ).toString());
        ShopModel shopModel = new ShopModel();
        shopModel.setShopId(id);
      if(jshoptable.getSelectedRow()>-1){
      int row = new ShopDaoImpl().deleteShopData(shopModel);
      if(row>0){
          new MessageForm("Success","Deleted","info.png").setVisible(true);
          fillShopTable();
      
      }else{
      new MessageForm("UnSuccess","Not Deleted","error.png").setVisible(true);
      }
      }else{
      new MessageForm("Please Select Row!!!","UnSuccess","error.png").setVisible(true);
      }
      
    }//GEN-LAST:event_DeleteActionPerformed

    private void jshoptableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jshoptableMouseReleased
       
        if (evt.isPopupTrigger()) {
        if(jshoptable.getSelectedRow()>-1){
            jpopup.show(jshoptable, evt.getX(), evt.getY());
        }
        }
    }//GEN-LAST:event_jshoptableMouseReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Delete;
    private javax.swing.JLabel addshop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu jpopup;
    private javax.swing.JTextField jshopname;
    private javax.swing.JTextField jshopquantity;
    private javax.swing.JTextField jshopsearch;
    private javax.swing.JTable jshoptable;
    private javax.swing.JLabel updateshop;
    // End of variables declaration//GEN-END:variables

    private void fillShopTable() {
        ShopDaoImpl shopDaoImpl = new ShopDaoImpl();
        ResultSet resultSet = shopDaoImpl.getAllShops();
        jshoptable.setModel(DbUtils.resultSetToTableModel(resultSet));
        
    }
}
